### ISSUE TITLE
app.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [volodya-bychko/Angular2Learn#2]
Предлагаю использовать следующую последовательность методов в компоненте:
1. конструктор
2. методы-хуки
3. публичные методы
4. приватные методы.

**Comment by volodya-bychko** [comment]
Thanks for review. Fixed in changeset https://github.com/volodya-bychko/Angular2Learn/commit/d5d506b2b2e03144087d26a366013537eb38f1e3
