### ISSUE TITLE
app.component.ts (private productService)

### ISSUE THREAD

**Issue by VZhyrytskiy** [volodya-bychko/Angular2Learn#3]
Предлагаю productsService не использовать в шаблоне компонента <app-cart *ngIf="this.productsService.getCartProducts().length > 0"></app-cart>, так как он приватный или сделать его публичным.

**Comment by volodya-bychko** [comment]
Thanks for review. Fixed in scope of commit https://github.com/volodya-bychko/Angular2Learn/commit/d5d506b2b2e03144087d26a366013537eb38f1e3
